POST http://localhost:8081/test_add_user
Content-Type: application/json

{
    "name": "John Doe",
    "avatar": "https://example.com/avatar.jpg",
    "email": "john2.doe@example.com",
    "phoneNumber": "1234567890",
    "username": "johndoe2",
    "password": "password123"
}