POST http://localhost:8081/signupPOST
Content-Type: application/json

{
    "name": "Phan Dinh Minh",
    "avatar": "http://example.com/avatar10.jpg",
    "email": "phandinhminh48@gamil.com",
    "phoneNumber": "012-345-6789",
    "username": "phandinhminh",
    "password": "securepassword10"
}