POST http://localhost:8081/addProjectPOST
Content-Type: application/json

{
    "manager": "67a45ac7cb4922dea9a3ebfd",
    "deadline": "2025-02-16T00:00:00Z",
    "title": "Test Project",
    "description": "This is a test project"
}